[package]
name = "r786"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
binary_search_range = { git = "https://github.com/ia7ck/rust-competitive-programming" }
