[package]
name = "yuki-1946"
version = "0.0.0"
edition = "2018"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
divisors = { git = "https://github.com/ia7ck/rust-competitive-programming" }
