[package]
name = "abc342"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
prime_factorization = { git = "https://github.com/ia7ck/rust-competitive-programming" }
segment_tree = { git = "https://github.com/ia7ck/rust-competitive-programming" }
