[package]
name = "abc238-g"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
least_prime_factors = { git = "https://github.com/ia7ck/rust-competitive-programming", rev = "9c9fc50" }
# itertools = { version = "=0.11.0" }
