[package]
name = "abc366"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
cumulative_sum_2d = { git = "https://github.com/ia7ck/rust-competitive-programming", rev = "9c9fc50" }
