[package]
name = "abc266"
version = "0.0.0"
edition = "2018"

[dependencies]
proconio = { version = "=0.3.6" }
detect_cycle = { git = "https://github.com/ia7ck/rust-competitive-programming" }
union_find = { git = "https://github.com/ia7ck/rust-competitive-programming" }