[package]
name = "abc328"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
itertools = { version = "0.11.0" }
union_find = { git = "https://github.com/ia7ck/rust-competitive-programming" }
