[package]
name = "abc352"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
memoise = { version = "=0.3.2" }
union_find = { git = "https://github.com/ia7ck/rust-competitive-programming" }
