[package]
name = "abc367"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
binary_search_range = { git = "https://github.com/ia7ck/rust-competitive-programming", rev = "9c9fc50" }
