[package]
name = "arc142"
version = "0.0.0"
edition = "2018"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
join = { git = "https://github.com/ia7ck/rust-competitive-programming" }
grid_search = { git = "https://github.com/ia7ck/rust-competitive-programming" }
