[package]
name = "abc362"
version = "0.0.0"
edition = "2021"

[dependencies]
proconio = { version = "=0.4.5" }
dijkstra = { git = "https://github.com/ia7ck/rust-competitive-programming" }
suffix_array = { git = "https://github.com/ia7ck/rust-competitive-programming" }
